### ISSUE TITLE
pip install fails due to netcdf4 trying to build from source on MacOS

### ISSUE THREAD

**Issue by cchwala** [pycomlink/pycomlink#159]
UPDATE: The errors below where on MacOS. Things work fine on Linux.

UPDATE2: The problem was my outdate MacOS version, see last comment in this issue.

------------------------------------------------

I tried to install v0.4.0 via pip in an empty conda env with Python 3.11. 

I get the following error which stems from netcdf4 trying to be built from source.

```
Collecting netcdf4 (from pycomlink)
  Using cached netcdf4-1.7.1.post2.tar.gz (827 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      reading from setup.cfg...
          HDF5_DIR environment variable not set, checking some standard locations ..
      checking /Users/chwala-c/miniforge3/envs/pycomlink_pip_test/include...
      hdf5 headers not found in /Users/chwala-c/miniforge3/envs/pycomlink_pip_test/include
      checking /Users/chwala-c/miniforge3/envs/pycomlink_pip_test/Library/include...
      hdf5 headers not found in /Users/chwala-c/miniforge3/envs/pycomlink_pip_test/Library/include
      checking /Users/chwala-c/include...
      hdf5 headers not found in /Users/chwala-c/include
      checking /usr/local/include...
      hdf5 headers not found in /usr/local/include
      checking /sw/include...
      hdf5 headers not found in /sw/include
      checking /opt/include...
      hdf5 headers not found in /opt/include
      checking /opt/local/include...
      hdf5 headers not found in /opt/local/include
      checking /opt/homebrew/include...
      hdf5 headers not found in /opt/homebrew/include
      checking /usr/include...
      hdf5 headers not found in /usr/include
      Traceback (most recent call last):
        File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8f/z1lq69v144zb2p1_l1twh7kh0006md/T/pip-build-env-8k_iz7ht/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8f/z1lq69v144zb2p1_l1twh7kh0006md/T/pip-build-env-8k_iz7ht/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/8f/z1lq69v144zb2p1_l1twh7kh0006md/T/pip-build-env-8k_iz7ht/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 277, in <module>
        File "<string>", line 226, in _populate_hdf5_info
      ValueError: did not find HDF5 headers
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

If I install older versions of netcdf4, e.g. 1.6.2, via pip in the same empty env, everything works.

There was a similar issue in https://github.com/Unidata/netcdf4-python/issues/1344 but the solution there was to install netcdf4 via conda, which is not what I need, because we finally want to have a working pip install of pycomlink...

**Comment by cchwala** [comment]
It works with forcing binary-only install

```
 pip install --only-binary=:all: pycomlink
```

**Comment by cchwala** [comment]
..but now I get a lot of errors when import `pycomlink`, e.g.

```python
#.
#..
#... longer trace above

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/__init__.py", line 6, in <module>
    from . import processing
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/processing/__init__.py", line 2, in <module>
    from . import baseline
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/processing/baseline.py", line 7, in <module>
    from .xarray_wrapper import xarray_apply_along_time_dim
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/processing/xarray_wrapper.py", line 4, in <module>
    import xarray as xr
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/xarray/__init__.py", line 3, in <module>
    from xarray import groupers, testing, tutorial
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/xarray/groupers.py", line 17, in <module>
    from xarray.coding.cftime_offsets import BaseCFTimeOffset, _new_to_legacy_freq
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/xarray/coding/cftime_offsets.py", line 56, in <module>
    from xarray.coding.cftimeindex import CFTimeIndex, _parse_iso8601_with_reso
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/xarray/coding/cftimeindex.py", line 54, in <module>
    from xarray.coding.times import (
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/xarray/coding/times.py", line 14, in <module>
    from xarray.coding.variables import (
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/xarray/coding/variables.py", line 14, in <module>
    from xarray.core.variable import Variable
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/xarray/core/variable.py", line 20, in <module>
    from xarray.core import common, dtypes, duck_array_ops, indexing, nputils, ops, utils
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/xarray/core/common.py", line 14, in <module>
    from xarray.core import dtypes, duck_array_ops, formatting, formatting_html, ops
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/xarray/core/ops.py", line 17, in <module>
    import bottleneck as bn
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/__init__.py", line 9, in <module>
    from . import validation
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/validation/__init__.py", line 13, in <module>
    from . import validator
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/validation/validator.py", line 10, in <module>
    import poligrain as plg
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/poligrain/__init__.py", line 15, in <module>
    import netCDF4  # noqa: F401
    ^^^^^^^^^^^^^^
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
  File "src/netCDF4/_netCDF4.pyx", line 1, in init netCDF4._netCDF4
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

There seemed to be a problem from `bottleneck` due to being compiled with older numpy.

After updating `bottleneck` to 1.4.0 via pip and building it from source, I still get this:


```python
>>> import pycomlink
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/__init__.py", line 9, in <module>
    from . import validation
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/validation/__init__.py", line 13, in <module>
    from . import validator
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/pycomlink/validation/validator.py", line 10, in <module>
    import poligrain as plg
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/poligrain/__init__.py", line 15, in <module>
    import netCDF4  # noqa: F401
    ^^^^^^^^^^^^^^
  File "/Users/chwala-c/miniforge3/envs/pycomlink_pip_test/lib/python3.11/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
  File "src/netCDF4/_netCDF4.pyx", line 1, in init netCDF4._netCDF4
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

So, using wheels also leads to dependency issues, but of the lower layer (C dependencies and the like...).

**Comment by cchwala** [comment]
after installing the last numpy1 version via
```
pip install numpy==1.26.4
```

importing `pycomlink` worked.

**Comment by cchwala** [comment]
...the problem is that I have an old MacOS version 🙈 

If I manually download the lastest NetCDF wheel and adjust the file name so it suggest that it was built for my current MacOS version, it installs and then imports without problems. Apparently, pip only checks compatibility with OS via the filename of the wheel.
